name: Linting

on:
  pull_request: {}
  push:
    branches:
        - main

permissions: read-all

jobs:
  check-backwards-compatability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            fetch-tags: true

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1
          opam-pin: false
          opam-depext: false
          dune-cache: true

      - run: opam install atd

      - name: atddiff all supported tags
        run: |
            set -e
            eval $(opam env)

            # fetch minimum version and enumerate tags for supported releases
            minimum="v$(curl -s https://semgrep.dev/api/check-version | jq -r '.versions.minimum')"
            tags=$(git log --simplify-by-decoration --pretty=format:%D "${minimum}^!" origin/main | grep -o 'tag: [^,)]\+' | sed 's/^tag: //' | sort -n)

            # check tags
            checked=()
            for tag in $tags; do
                commit=$(git rev-list -n 1 "$tag")
                if [[ "${checked[*]}" =~ $commit ]]; then
                    echo "Skipping $tag because commit $commit has already been checked"
                    continue
                fi
                checked+=($commit)

                echo "Checking backward compatibility of semgrep_output_v1.atd against past version $tag"
                git difftool -x 'atddiff --backward' -y --trust-exit-code "$tag" semgrep_output_v1.atd
            done
