name: Linting

on:
  pull_request: {}
  push:
    branches:
        - main

permissions: read-all

jobs:
  compatability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            fetch-tags: true

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1
          opam-pin: false
          opam-depext: false
          dune-cache: true

      - name: install atddiff
        run: opam install atd

      - name: atddiff all supported tags
        shell: bash
        run: |
            eval $(opam env)

            # fetch minimum version and enumerate tags for supported releases
            minimum="v$(curl -s https://semgrep.dev/api/check-version | jq -r '.versions.minimum')"
            tags=$(git log --simplify-by-decoration --pretty=format:%D "${minimum}^!" origin/main | grep -o 'tag: [^,)]\+' | sed 's/^tag: //' | sort -n)

            # check tags
            set +xo pipefail # take care of error handling ourselves from here
            checked=()
            errors=0
            for tag in $tags; do
                commit=$(git rev-list -n 1 "$tag")
                if [[ "${checked[*]}" =~ $commit ]]; then
                    echo "Skipping $tag because commit $commit has already been checked"
                    continue
                fi
                checked+=($commit)

                echo "Checking backward compatibility of semgrep_output_v1.atd against past version $tag"
                git difftool -x 'atddiff --backward' -y --trust-exit-code "$tag" semgrep_output_v1.atd

                if [ $? -ne 0 ]; then
                    echo "ERROR: semgrep_output_v1.atd is not backward compatible with $tag"
                    errors=$((errors + 1))
                fi
            done

            if [ $errors -eq 0 ]; then
                exit 1
            fi